### ISSUE TITLE
Fix Artifacts

### ISSUE THREAD

**Issue by GDcheeriosYT** [GDcheeriosYT/Gentrys-Quest-Python#20]
There are a lot of bugs with managing artifacts.

1. Artifacts aren't removed from the list when managing them if they're not equipped to a character.
![WindowsTerminal_ST4FSFI8l4](https://user-images.githubusercontent.com/54640414/200879609-231e735d-1367-46be-92fd-00a274760a9d.gif)

2. Artifacts can be duplicated. Removing an artifact should only be an option if the artifact is equipped.
![WindowsTerminal_eubUvrgbAC](https://user-images.githubusercontent.com/54640414/200880178-639fe3ee-5da1-4032-a556-be9dc5b47e53.gif)

**Comment by carterballard123** [comment]
hI:), fixed a bug where it allowed you to access the artifact menu when you didnt have any artifacts.

**Comment by GDcheeriosYT** [comment]
I fixed the 2nd topic here

**Comment by carterballard123** [comment]
HEY, WHEN YOU SWITCH ARTIFACTS IN THE ARTIFACT MENU, THE ITEM DUPLICATES

**Comment by GDcheeriosYT** [comment]
> HEY, WHEN YOU SWITCH ARTIFACTS IN THE ARTIFACT MENU, THE ITEM DUPLICATES

hey, that's crazy but I didn't ask. Get ratioed

**Comment by GDcheeriosYT** [comment]
JK, good to know. 👍

**Comment by GDcheeriosYT** [comment]
artifact levels carry over in inventory...
```
1. kfc fries ★★★☆☆ level 2/16 42xp
2. lucas's iphone ★★★☆☆ level 2/16 42xp
3. lucas's iphone ★☆☆☆☆ level 2/16 42xp
4. lucas's iphone ★★★★☆ level 2/16 42xp
```

**Comment by GDcheeriosYT** [comment]
I've realized how broken artifacts are. When testing artifacts, the main attribute buff stat type is one index off. When I choose attack it ends up being health.

**Comment by GDcheeriosYT** [comment]
> I've realized how broken artifacts are. When testing artifacts, the main attribute buff stat type is one index off. When I choose attack it ends up being health.

I just fixed this. the problem was that it was calling `StatTypes(counter)` which would be one number off because of:
```
Health = 1
Attack = 2Defense = 3
    CritRate = 4
    CritDamage = 5
    ```

**Comment by GDcheeriosYT** [comment]
I've been working on this for like 4 hours now. I've fixed most of these issues. I'm still working on removing artifacts from character's artifact list causing duplicates in inventory's artifact list.

**Comment by GDcheeriosYT** [comment]
Just noticed that artifact levels aren't set when loading data.

**Comment by GDcheeriosYT** [comment]
Noticed how character stats change every startup. Pretty sure it has to do with artifacts and how they're loaded.

**Comment by GDcheeriosYT** [comment]
I have fixed most of the stuff. One more thing.
```
TardySlip *
apart of the Lucas Smidt family
level 2/4 10xp/178xp (10)%
* Attack 4 *
```
percentage calculation seems off.

**Comment by GDcheeriosYT** [comment]
> I have fixed most of the stuff. One more thing.
> 
> ```
> TardySlip *
> apart of the Lucas Smidt family
> level 2/4 10xp/178xp (10)%
> * Attack 4 *
> ```
> 
> percentage calculation seems off.

I fixed it! I put a paratheses to early on making it multiply by 100.
